// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;



contract Struct {
  //The struct helps to organize the detail of an object let say Todo
  struct Todo {
    string text;
    bool completed;
  }

  Todo[] public todos;  // Array of Todo struct

  //calldata ensures your variable are explicitly stored within the function  
  function set(string calldata _text) public {
    todos.push(Todo(_text, false));
    //Struct could also be initialized by
    // todos.push(Todo({text: _text, completed: false})) Explicitly
  }

  // A getter function for the Struct is implicitly generated by solidity

  function updateText(uint _index, string calldata _text) public {
    Todo storage todo = todos[_index];
    todo.text = _text;
  }

  function toggleCompleted(uint _index) public {
    Todo storage todo = todos[_index];
    todo.completed = !todo.completed;
  }
}